project:
  type: website

website:
  title: "AI in the Screen Sector: Casebook"
  favicon: images/favicon.ico
  navbar:
    logo: images/header-logos-2026-brand.png
    title: false
    right:
      - href: index.qmd
        text: Overview
      - href: case-studies/index.qmd
        text: Case studies
      - href: digest/index.qmd
        text: Digest

  page-footer:
    background: "#ffffff"
    left:
      - text: "costarnetwork.co.uk"
        href: https://www.costarnetwork.co.uk/labs/foresightlab
    center: Funded by [![](/images/ahrc-logo.png)](https://www.ukri.org/councils/ahrc/remit-programmes-and-priorities/convergent-screen-technologies-and-performance-in-realtime-costar/)
    right:
      - href: https://github.com/costar-foresight-lab/ai-casebook
        icon: github
        aria-label: GitHub
      - href: https://www.linkedin.com/showcase/costar-foresight-lab
        icon: linkedin
        aria-label: LinkedIn


format:
  html:
    theme: [cosmo, styles.scss]
    css: styles.css
    toc: true



