---
title: "AI in the Creative Industries: Quarterly Digest - April to June 2026"
description: "As prominent film industry figures become involved in AI-related projects, a survey finds authors split on AI use, while tech commentators remain divided on whether AI will lead to a net increase or decrease in jobs."  
author: Petra Lindnerova
categories:
  - Sector adaptation
  - Independent creation
  - Public transparency
  - Skills
  - Investment
citation:
  publisher: CoSTAR Foresight Lab
  container-title: "AI in the Screen Sector: Quarterly Digest"
date: 07/14/2026
toc: true
# image:
# image-alt:
---

*In this digest, we analyse developments thematically, linking them to the nine key recommendations defined in our June 2025 report, ‘AI in the Screen Sector: Perspectives and Paths Forward’. Through monitoring of news items, reports and publications, the digest highlights emerging industry trends and tracks whether the sector is moving towards or away from the report's recommendations that, as of June 2025, attempted to represent ideal outcomes for the sector. From the 'April to June 2026' issue of the Digest, our research expands beyond the screen sector into other areas of the creative industries such as book publishing and music.*

## Sector adaptation

The latest quarter saw prominent film industry figures get involved in AI-related projects, albeit on differing levels. Pulp Fiction co-writer [Roger Avary](https://deadline.com/2026/04/roger-avary-direct-biblical-paradise-lost-ai-production-1236875688/) has agreed to write and direct Paradise Lost, based on the epic 17th century poem, for an ‘AI-oriented’ company called Ex Machina. Steven Soderbergh has talked about using AI in his documentary [John and Yoko](https://deadline.com/2026/04/steven-soderbergh-use-lot-of-ai-spanish-american-war-movie-1236785093/) to produce ‘thematically surreal images’ to accompany philosophical discussions in the film. Darren Aronofsky’s AI-generated series On this Day...1776 has continued despite [poor critical reception](https://www.theguardian.com/film/2026/feb/02/darren-aronofsky-ai-revolutionary-war-series-review), with the director stating that this ‘experiment’ serves as a great example of how AI is going to advance. Meanwhile, a new short film from Aronofsky’s AI-filmmaking company [Primordial Soup](https://deadline.com/2026/05/darren-aronofsky-1776-primordial-soup-ai-cannes-1236907148/) and Google DeepMind made the Cannes Classics Official Selection: [Goodnight Lamby](https://www.indiewire.com/features/general/dustin-yellin-goodnight-lamby-gen-ai-cannes-1235197275/) ‘incorporates live action, photography, collage-like animation, and generative AI using Google Veo 3’. Finally, Martin Scorsese, having taken up an advisory role for AI company Black Forest Labs, discussed his interest ‘in the intersection of technology and storytelling’ and his use of the company’s [FLUX](https://variety.com/2026/film/news/martin-scorsese-supports-ai-company-storyboard-movies-1236765037/) tool for storyboarding ideas.

In books, writer [Anthony Horowitz](https://www.independent.co.uk/arts-entertainment/books/news/anthony-horowitz-books-chatgpt-ai-b2971205.html) admitted to using AI for research, claiming ‘it feels like cheating’, while Nobel Prize winner [Olga Togarczuk](https://lithub.com/nobel-laureate-olga-tokarczuk-apparently-used-ai-to-write-her-latest-novel/) attracted negative attention after describing how she worked with AI during the writing process for her latest novel, and referring to the AI as ‘kochana’, which can be translated from Polish as ‘beloved’. She added: ‘Even though I know about hallucinations and many factual errors in the algorithms in terms of economics and hard data, I have to add that in literary fiction this technology is an advantage of unbelievable proportion.’ According to results of a [survey](https://insights.bookbub.com/how-authors-are-thinking-about-ai-survey/) conducted by BookBub, authors are split almost evenly on AI use: about 45% of the 1,200 respondents say they use generative AI to assist with their work, while 48% do not and have no intention of doing so.

In a bid to plug AI films further into the mainstream market, the first [World AI Film Festival](https://www.theguardian.com/technology/2026/apr/26/cannes-ai-film-festival-raises-eyebrows-questions-future?CMP=Share_AndroidApp_Other) – backed by big tech firms – was held in Cannes amid rising interest from Hollywood players keen on [producing multiple lower-budget AI films](https://www.axios.com/2026/03/18/hollywood-ai-amazon-netflix) over one ‘conventional’, more expensive film. As per media reports, the festival felt ‘raw and patchy’, and the showcased projects were described as often dystopian, favouring the demonstration of technical skills while compromising ‘narrative heart’. This aligns with [audience sentiment](https://variety.com/2026/film/features/i-saw-hell-grind-ai-generated-film-cannes-shocking-realistic-1236770720/) toward ‘Hell Grind’, an AI film created by Higgsfield, which premiered at Marche du Film and was reviewed as being ‘technically impressive but makes the limits of AI visible’.

## Independent creation

Established studios are tapping independent creators to work with them on AI-first productions. In May, Amazon MGM Studios launched the [Gen AI Creators’ Fund](https://variety.com/2026/film/news/amazon-mgm-studios-genai-creators-fund-greenlights-series-1236759131/), an initiative to accelerate adoption and provide opportunities to creators developing AI works. It has already resulted in three commissions by Amazon Prime. Meanwhile, [Gossip Goblin](https://www.theguardian.com/technology/2026/may/14/gossip-goblin-ai-film-making-new-era-hollywood) caught the attention of Hollywood, including ‘heavyweight LA talent agents, movie producers, screenwriters, studios, streamers and A-list actors’, after accumulating millions of views on its YouTube channel.

In model development news, Seedance 2.0 launched globally despite [industry-wide backlash](https://www.theguardian.com/film/2026/feb/13/new-ai-video-generator-seedance-tom-cruise-brad-pitt?CMP=Share_AndroidApp_Other) over its IP infringement, and [ElevenLabs](https://www.votemyai.com/blog/elevenlabs-elevenmusic-app-suno-udio-competitor.html) released a prompt-to-song app as part of its developing audio platform, complete with voice synthesis and sound effects.

[The Atlantic](https://www.theatlantic.com/technology/2026/06/ai-music-generators-suno-google-udio/687485/) continued its investigations into AI model development and the datasets used to train AI. Having previously documented datasets containing libraries of books and movie dialogue, its latest report focuses on the discovery of four datasets with over 20 million songs that are readily available online for AI developers – one of them having been used by Google. The datasets are listed on AI data-sharing sites or in research papers published by developers. Media platforms are exploring formalised approaches to allow creative reuse of content within consumer-facing AI applications. Spotify struck a [licensing deal](https://newsroom.spotify.com/2026-05-21/universal-music-group-spotify-licensing-agreements-fan-made-covers-remixes/) with Universal as part of plans for a paid add-on feature, ‘grounded in consent, credit and compensation’, that would allow fans to create remixes of works by included artists. Meanwhile, [YouTube](https://www.youtube.com/watch?v=EdjpqqwUjhs) has introduced a new ‘Remix’ feature for users to ‘repurpose and reimagine’ existing video content, with credit given to the original creator.

## Public transparency

Further accusations of undeclared AI use have hit the headlines. When the Commonwealth Short Story Prize 2026 announced its winner, [critics](https://www.theguardian.com/books/2026/jul/01/judges-claims-ai-use-commonwealth-short-story-prize-jamir-nazir) alleged that the overall prize-winning work bore ‘significant markers of AI use’. AI-detection software [Pangram](https://lithub.com/a-prize-winning-story-published-in-granta-was-very-likely-written-by-ai/) was used to analyse the story written by overall winner Jamir Nazir, and reportedly ‘came back with 100% red flags’. Competition judges refused to rely solely on AI-detection software, however, and instead [requested](https://commonwealthfoundation.com/2026-cw-prize-update/) that the regional winners of the competition share time-stamped drafts and outlines of their stories to evidence their writing process. The submitted materials were considered satisfactory, according to the director of the Commonwealth Foundation. Even so, Granta magazine terminated its partnership with the competition and will no longer publish winning entries.

American band [Zao](https://lambgoat.com/news/52867/zao-flagged-by-tunecore-for-using-generative-ai-delaying-new-release/) also opted for process transparency when flagged for AI use by digital distribution service TuneCore: they retrospectively shared early mixes of their latest release to clear their name.

The film industry continued to draw boundaries around the use of artificial intelligence in creative outputs. In May, SAG-AFTRA ratified a [new contract](https://variety.com/2026/film/news/sag-aftra-ratification-ai-pension-merger-1236767288/) that includes protections against synthetic performers, stipulating that producers may only use AI-generated actors when they provide ‘significant additional value’ beyond what a live performer or existing digital replica can offer.

The Oscars tightened their approach to AI in awards eligibility. Under new [rules](https://www.thewrap.com/industry-news/awards/oscars-rule-changes-2026-ai-actors/), fully AI-generated performances and AI-written screenplays are not eligible for Oscar recognition. While filmmakers may continue to use AI tools during production, the Academy made clear that the core artistic contributions recognised by the Oscars must come from human creators.

## Skills

Major global firms cut back on roles while pushing investment in AI: [Meta](https://www.nytimes.com/2026/05/19/technology/meta-layoffs-ai.html) let go of 8,000 workers, with another 7,000 employees reassigned to teams working across AI initiatives, and [Microsoft](https://www.theguardian.com/technology/2026/apr/23/meta-microsoft-tech-ai-layoffs) offered voluntary retirement to 7% of their staff while predicting spend of nearly £100 billion on AI infrastructure. These examples reflect a broader strategy focused on streamlining workforce and cross-organisational AI implementation. At the same time, [Uber](https://www.theverge.com/transportation/937116/uber-ai-investment-hard-to-justify) revealed that it had exhausted its Claude Code budget for 2026 within just four months without producing visible efficiencies. According to chief operating officer Matthew Macdonald, the investment in AI is getting ‘harder to justify’.

These developments fuelled the ongoing debate on whether AI will lead to a net increase or decrease in jobs. A recent [Morgan Stanley survey](https://www.theguardian.com/technology/2026/jan/26/ai-uk-jobs-us-japan-germany-australia) provided evidence that the UK is currently losing more jobs than it creates. Former UK Prime Minister [Rishi Sunak](https://www.bbc.co.uk/news/articles/cvg07x4rejdo), for example, has argued that AI is ‘flattening’ the labour market, with chief executives aiming to expand their firms via deployment of AI instead of increasing their workforce. He is asking policymakers to rethink taxation: specifically, to get rid of National Insurance and rebalancing it with taxes on corporate profits, therefore making it more cost-effective for companies to hire workers. Meanwhile, OpenAI CEO [Sam Altman](https://www.reuters.com/world/asia-pacific/openais-altman-says-ai-unlikely-lead-jobs-apocalypse-2026-05-26/) stated that predicted white-collar job losses have not materialised as quickly as expected, and that the technology’s impact has so far been less disruptive than many feared. But Palantir CEO Alex Karp [warned](https://fortune.com/2026/06/09/palantir-ceo-alex-karp-massive-ai-layoffs-may-be-bad-for-industry-future-of-work-bernie-sanders-headcount-reductions/) that a public backlash is likely if tech leaders continue celebrating AI-driven layoffs.

## Investment

Despite uncertainty surrounding large-scale AI infrastructure projects, the UK government continued to advocate for wider adoption of artificial intelligence. While the multi-billion-pound UK-US data centre project [Stargate](https://www.bbc.co.uk/news/articles/clyd032ej70o) was put on ice due to arising regulatory challenges and energy costs, technology secretary Liz Kendall urged businesses and the public to embrace AI and seize its economic potential. In support of this goal, the government announced £500 million of [investment](https://www.theguardian.com/technology/2026/apr/17/liz-kendall-urges-uk-public-to-embrace-ai-as-government-makes-first-500m-fund-investment) through its Sovereign AI fund, arguing that the UK must capitalise on the opportunities presented by the technology despite ongoing concerns over job displacement and security risks. The government invested in London-based AI infrastructure company Callosum, and an unnamed second business. Six UK companies are to receive access to a network of government-funded supercomputers to help them develop AI models in exchange for ‘a right of first refusal’ to invest in some of those firms.

In terms of private-sector investment, [AMD](https://ir.amd.com/news-events/press-releases/detail/1288/amd-commits-up-to-2-billion-to-accelerate-ai-innovation-and-research-in-the-united-kingdom) committed up to £2 billion to expand its presence in the UK, while [Google](https://variety.com/2026/film/news/google-a24-ai-filmmaking-tools-1236787297/) invested £57 million in A24 to help develop AI-powered filmmaking tools. A24 partner Scott Belsky, whose division is working on developing applications for AI storyboards similar to ones championed by Scorsese, argued the new tools ‘won’t look anything like the prompted generation type of AI that people feel uncomfortable with’. The deal does not include access to A24 library data.  

::: {.grid .gap-3 .pb-3 .pt-4}
::: {.g-col-12 .g-col-sm-6}

[Read more from the digest](/digest/index.qmd){.btn-action .btn .btn-lg .w-100 role="button"}

:::
::: {.g-col-12 .g-col-sm-6 .mb-2}

[Explore AI case studies](/case-studies/index.qmd){.btn-action .btn .btn-lg .w-100 role="button"}

::: 
::: 